//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Alba_alertas_alba
    {
        public int id_alerta_alba { get; set; }
        public int id_estatus_alerta { get; set; }
        public string nombre { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public int id_tipo_edad { get; set; }
        public int edad { get; set; }
        public System.DateTime fecha_desaparicion { get; set; }
        public string lugar_desaparicion { get; set; }
        public int id_tipo_estatura { get; set; }
        public double estatura { get; set; }
        public int peso { get; set; }
        public string complexion { get; set; }
        public string tez { get; set; }
        public string ojos { get; set; }
        public string nariz { get; set; }
        public string boca { get; set; }
        public string cabello { get; set; }
        public string senas_particulares { get; set; }
        public string vestimenta { get; set; }
        public string resumen_hechos { get; set; }
        public string url_imagen { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public int prioridad { get; set; }
    }
}
