//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Amber_alertas_amber
    {
        public int id_alerta_amber { get; set; }
        public int id_estatus_alerta { get; set; }
        public string nombre { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public System.DateTime fecha_hechos { get; set; }
        public Nullable<int> id_tipo_edad { get; set; }
        public int edad { get; set; }
        public string nacionalidad { get; set; }
        public int genero { get; set; }
        public string cabello { get; set; }
        public string ojos { get; set; }
        public Nullable<int> id_tipo_estatura { get; set; }
        public double estatura { get; set; }
        public int peso { get; set; }
        public string senas_particulares { get; set; }
        public string lugar_hechos { get; set; }
        public string resumen_hechos { get; set; }
        public string url_imagen { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public int prioridad { get; set; }
        public Nullable<bool> tiene_info_adicional { get; set; }
        public Nullable<int> id_tipo_calidad { get; set; }
        public string url_imagen_adicional { get; set; }
        public string nombre_adicional { get; set; }
        public string descripcion_adicional { get; set; }
    }
}
