//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agencias
    {
        public short Cve_age { get; set; }
        public string Desc_age { get; set; }
        public int Cve_area { get; set; }
        public string Cve_ubica { get; set; }
        public string Desc_doc { get; set; }
        public string No_age { get; set; }
        public string Extension { get; set; }
        public string Municipio { get; set; }
        public string Adscripcion { get; set; }
        public string Siglas { get; set; }
        public int Age_Deter_Reser { get; set; }
        public int Num_Ordenado { get; set; }
        public short Guardia { get; set; }
        public Nullable<System.DateTime> Fecha_Guardia { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> Cve_Calle { get; set; }
        public string NoCasa { get; set; }
        public Nullable<int> Id_Partido { get; set; }
        public Nullable<int> Id_Adscripcion { get; set; }
        public int Tipo { get; set; }
        public string no_telefonico { get; set; }
        public string horario { get; set; }
        public Nullable<int> CveAgenciaOrigen { get; set; }
        public Nullable<int> UnidadID { get; set; }
        public string Agencia { get; set; }
    }
}
