//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alias
    {
        public string ALIAS1 { get; set; }
        public System.DateTime FEC_ALI { get; set; }
        public int CLAVE_PERSO { get; set; }
        public int miconse { get; set; }
        public System.DateTime fec_captu { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
