//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calles
    {
        public decimal Cve_Calle { get; set; }
        public string Calle { get; set; }
        public Nullable<decimal> Cve_Col { get; set; }
        public int Correcto { get; set; }
        public System.Guid rowguid { get; set; }
    
        public virtual Colonia Colonia { get; set; }
    }
}
