//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capea_boletin_busqueda
    {
        public int id_boletin_busqueda { get; set; }
        public int id_estatus_boletin { get; set; }
        public string nombre { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public int edad { get; set; }
        public int sexo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public System.DateTime fecha_ausencia { get; set; }
        public string lugar_ausencia { get; set; }
        public double estatura { get; set; }
        public int peso { get; set; }
        public string complexion { get; set; }
        public string tez { get; set; }
        public string cara { get; set; }
        public string frente { get; set; }
        public string tipo_color_cabello { get; set; }
        public string cejas { get; set; }
        public string tipo_color_ojos { get; set; }
        public string nariz { get; set; }
        public string boca { get; set; }
        public string menton { get; set; }
        public string senas_particulares { get; set; }
        public string vestimenta { get; set; }
        public string observaciones { get; set; }
        public string url_imagen { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public int prioridad { get; set; }
    }
}
