//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_TipoAgrupacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_TipoAgrupacion()
        {
            this.tb_Grupo_Delictivo = new HashSet<tb_Grupo_Delictivo>();
        }
    
        public int int_id_tipo_agrupacion { get; set; }
        public string nvarchar_agrupacion { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Grupo_Delictivo> tb_Grupo_Delictivo { get; set; }
    }
}
