//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_EstatusProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_EstatusProceso()
        {
            this.tb_FichaObjetivo = new HashSet<tb_FichaObjetivo>();
        }
    
        public int int_id_estatus_proceso { get; set; }
        public string nvarchar_estatus { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FichaObjetivo> tb_FichaObjetivo { get; set; }
    }
}
