//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Faltas
    {
        public int IdFueroComun { get; set; }
        public string FueroComun { get; set; }
        public Nullable<int> IdTipoFuero { get; set; }
        public string Municipio { get; set; }
    }
}
