//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_Perfil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_Perfil()
        {
            this.tb_PerfilFuenteBusqueda = new HashSet<tb_PerfilFuenteBusqueda>();
            this.tb_PerfilModulo = new HashSet<tb_PerfilModulo>();
            this.tb_PerfilPermiso = new HashSet<tb_PerfilPermiso>();
            this.tb_UsuarioPerfil = new HashSet<tb_UsuarioPerfil>();
        }
    
        public int int_id_perfil { get; set; }
        public string nvarchar_clave { get; set; }
        public string nvarchar_nombre { get; set; }
        public string nvarchar_descripcion { get; set; }
        public bool bit_status { get; set; }
        public System.DateTime date_fecha_alta { get; set; }
        public Nullable<System.DateTime> date_fecha_modificacion { get; set; }
        public string nvarchar_usuario_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PerfilFuenteBusqueda> tb_PerfilFuenteBusqueda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PerfilModulo> tb_PerfilModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PerfilPermiso> tb_PerfilPermiso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UsuarioPerfil> tb_UsuarioPerfil { get; set; }
    }
}
