//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_PermisoSistema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_PermisoSistema()
        {
            this.tb_PerfilPermiso = new HashSet<tb_PerfilPermiso>();
        }
    
        public int int_id_permiso { get; set; }
        public string nvarchar_clave { get; set; }
        public string nvarchar_nombre { get; set; }
        public string nvarchar_descripcion { get; set; }
        public bool bit_status { get; set; }
        public System.DateTime date_fecha_alta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PerfilPermiso> tb_PerfilPermiso { get; set; }
    }
}
