//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COINCIDENCIA
    {
        public int Id { get; set; }
        public int DetenidoId { get; set; }
        public int DetenidoCoincidenciaId { get; set; }
        public string TipoCoincidencia { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
