//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colonia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Colonia()
        {
            this.Calles = new HashSet<Calles>();
        }
    
        public decimal Cve_col { get; set; }
        public string Colonia1 { get; set; }
        public Nullable<int> Cve_mun { get; set; }
        public string CP { get; set; }
        public int Cve_colonia_ARC { get; set; }
        public int SecParti { get; set; }
        public bool Sedeso { get; set; }
        public string Colonia_Doctos { get; set; }
        public int Sector { get; set; }
        public System.Guid rowguid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Calles> Calles { get; set; }
    }
}
