//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_UnidadesInvestigacion
    {
        public int ID { get; set; }
        public string Unidad { get; set; }
        public bool Activa { get; set; }
        public Nullable<int> AreaID { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string DomicilioUnidad { get; set; }
        public string Titular { get; set; }
    }
}
