//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Del_x_in
    {
        public System.DateTime FE_DELI { get; set; }
        public string DEL_OBSE { get; set; }
        public int CLAVE_PERSO { get; set; }
        public int CLA_DELITO { get; set; }
        public System.DateTime fec_captu { get; set; }
        public int id { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
