//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETENIDO
    {
        public int IDDETENIDO { get; set; }
        public Nullable<int> IDDETENCION { get; set; }
        public string NOMBRE { get; set; }
        public string ALIAS { get; set; }
        public string EDAD { get; set; }
        public string ORIGINARIO { get; set; }
        public string SEXO { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string CP { get; set; }
        public string MUNICIPIO { get; set; }
        public Nullable<int> NUMEXT { get; set; }
        public string NUMINT { get; set; }
        public string Ap_Paterno { get; set; }
        public string Ap_Materno { get; set; }
        public string Ocupacion { get; set; }
        public string CaracteristicasDetenido { get; set; }
        public string Estado { get; set; }
        public string Folio { get; set; }
        public string Situacion { get; set; }
        public string Telefono { get; set; }
        public string Estatus { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public string RFC { get; set; }
        public string CURP { get; set; }
    }
}
