//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETENCION
    {
        public int IDDETENCION { get; set; }
        public string SERIE_MUNICIPIO { get; set; }
        public string CONSECUTIVO { get; set; }
        public string ANO { get; set; }
        public Nullable<System.DateTime> FECHA_DETENCION { get; set; }
        public string HORA_DETENCION { get; set; }
        public string FUERO { get; set; }
        public Nullable<int> NoDETENIDOS { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string CP { get; set; }
        public string MUNICIPIO { get; set; }
        public string HECHO { get; set; }
        public string CAUSA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> VECHICULO { get; set; }
        public Nullable<int> NUMEXT { get; set; }
        public string NUMINT { get; set; }
        public Nullable<decimal> Gramos { get; set; }
        public string Mes { get; set; }
        public string Dia { get; set; }
        public Nullable<bool> Feria { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string Aseguramientos { get; set; }
        public string Envoltorios { get; set; }
        public string Armas { get; set; }
        public string Cartuchos { get; set; }
        public string FueroDescripcion { get; set; }
        public string Cargadores { get; set; }
        public string OficialTraslada { get; set; }
    }
}
