//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domicilios
    {
        public int Id { get; set; }
        public int Clave_Perso { get; set; }
        public System.DateTime Fecha_Aprox_Vivia { get; set; }
        public System.DateTime Fecha_Alta { get; set; }
        public int Cla_Calle { get; set; }
        public string Num_Casa { get; set; }
        public int Actual { get; set; }
        public string CoordX { get; set; }
        public string CoordY { get; set; }
        public string MapaLogin { get; set; }
        public int MapaCve_Usuario { get; set; }
        public System.DateTime MapaFechaAct { get; set; }
        public string MapaHoraAct { get; set; }
        public string MapaLogin_Red { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
