//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public string Cve_Edo { get; set; }
        public string Estado1 { get; set; }
        public string Siglas { get; set; }
        public Nullable<int> SNSP_Cla_Edo { get; set; }
        public System.Guid rowguid { get; set; }
        public string Cve_Edo_Exhorto { get; set; }
        public int ID_Estado { get; set; }
    }
}
