//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Filiacion_MunicipiosEntities : DbContext
    {
        public Filiacion_MunicipiosEntities()
            : base("name=Filiacion_MunicipiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_TbFuente> cat_TbFuente { get; set; }
        public virtual DbSet<cat_TipoAlerta> cat_TipoAlerta { get; set; }
        public virtual DbSet<tb_Alerta> tb_Alerta { get; set; }
        public virtual DbSet<tb_DETENCION_C5> tb_DETENCION_C5 { get; set; }
        public virtual DbSet<tb_DETENIDO_C5> tb_DETENIDO_C5 { get; set; }
        public virtual DbSet<tb_FOTO_C5> tb_FOTO_C5 { get; set; }
        public virtual DbSet<tb_HUELLA_C5> tb_HUELLA_C5 { get; set; }
        public virtual DbSet<tb_PersonaBusqueda> tb_PersonaBusqueda { get; set; }
    
        public virtual ObjectResult<sp_Alertas_Result> sp_Alertas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Alertas_Result>("sp_Alertas");
        }
    
        public virtual ObjectResult<sp_BuscarDetenido_Result> sp_BuscarDetenido(Nullable<int> iDDETENIDO)
        {
            var iDDETENIDOParameter = iDDETENIDO.HasValue ?
                new ObjectParameter("IDDETENIDO", iDDETENIDO) :
                new ObjectParameter("IDDETENIDO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarDetenido_Result>("sp_BuscarDetenido", iDDETENIDOParameter);
        }
    }
}
