//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Filiacion_MunicipiosEntities : DbContext
    {
        public Filiacion_MunicipiosEntities()
            : base("name=Filiacion_MunicipiosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_TbFuente> cat_TbFuente { get; set; }
        public virtual DbSet<cat_TipoAlerta> cat_TipoAlerta { get; set; }
        public virtual DbSet<tb_Alerta> tb_Alerta { get; set; }
    }
}
