//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FiliacionEntities : DbContext
    {
        public FiliacionEntities()
            : base("name=FiliacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Nom_perso> Nom_perso { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Del_x_in> Del_x_in { get; set; }
        public virtual DbSet<Domicilios> Domicilios { get; set; }
        public virtual DbSet<dtproperties> dtproperties { get; set; }
        public virtual DbSet<Alias> Alias { get; set; }
        public virtual DbSet<Ingresos> Ingresos { get; set; }
    
        public virtual ObjectResult<SP_ObjPri_getFiliObjetivoClavePersona_Result> SP_ObjPri_getFiliObjetivoClavePersona(Nullable<int> clave_persona)
        {
            var clave_personaParameter = clave_persona.HasValue ?
                new ObjectParameter("clave_persona", clave_persona) :
                new ObjectParameter("clave_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObjPri_getFiliObjetivoClavePersona_Result>("SP_ObjPri_getFiliObjetivoClavePersona", clave_personaParameter);
        }
    
        public virtual ObjectResult<SP_ObjPri_getFiliObjetivoInfo_Result> SP_ObjPri_getFiliObjetivoInfo(Nullable<int> movimiento, string nombre, string paterno, string materno, string numavp, Nullable<int> clave_persona)
        {
            var movimientoParameter = movimiento.HasValue ?
                new ObjectParameter("movimiento", movimiento) :
                new ObjectParameter("movimiento", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            var numavpParameter = numavp != null ?
                new ObjectParameter("numavp", numavp) :
                new ObjectParameter("numavp", typeof(string));
    
            var clave_personaParameter = clave_persona.HasValue ?
                new ObjectParameter("clave_persona", clave_persona) :
                new ObjectParameter("clave_persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObjPri_getFiliObjetivoInfo_Result>("SP_ObjPri_getFiliObjetivoInfo", movimientoParameter, nombreParameter, paternoParameter, maternoParameter, numavpParameter, clave_personaParameter);
        }
    
        public virtual ObjectResult<SP_ObjPri_getListinfogeneral_Result> SP_ObjPri_getListinfogeneral(string nombre, string paterno, string materno)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObjPri_getListinfogeneral_Result>("SP_ObjPri_getListinfogeneral", nombreParameter, paternoParameter, maternoParameter);
        }
    
        public virtual ObjectResult<SP_SIC_getCoincidenciasDetenidos_Result> SP_SIC_getCoincidenciasDetenidos(string ids_nom_perso, string claves_perso)
        {
            var ids_nom_persoParameter = ids_nom_perso != null ?
                new ObjectParameter("ids_nom_perso", ids_nom_perso) :
                new ObjectParameter("ids_nom_perso", typeof(string));
    
            var claves_persoParameter = claves_perso != null ?
                new ObjectParameter("claves_perso", claves_perso) :
                new ObjectParameter("claves_perso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SIC_getCoincidenciasDetenidos_Result>("SP_SIC_getCoincidenciasDetenidos", ids_nom_persoParameter, claves_persoParameter);
        }
    }
}
