//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fiscalia_webEntities : DbContext
    {
        public fiscalia_webEntities()
            : base("name=fiscalia_webEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capea_boletin_busqueda> Capea_boletin_busqueda { get; set; }
        public virtual DbSet<A_Alba_alertas_alba> A_Alba_alertas_alba { get; set; }
        public virtual DbSet<A_Amber_alertas_amber> A_Amber_alertas_amber { get; set; }
    }
}
