//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public System.DateTime FE_INGRE { get; set; }
        public string HO_INGRE { get; set; }
        public string PER_DETE { get; set; }
        public int CONSIGNA { get; set; }
        public string LUCONSIGNA { get; set; }
        public string CONSIOBSE { get; set; }
        public string LU_DETEN { get; set; }
        public System.DateTime FEC_DET { get; set; }
        public string HORA_DET { get; set; }
        public string MOT_DET { get; set; }
        public string MP { get; set; }
        public string NUM_AVP { get; set; }
        public Nullable<int> DETENIDO { get; set; }
        public string DISPOSIDE { get; set; }
        public string NUM_ORD { get; set; }
        public string DETENPOR { get; set; }
        public string ENTIFED { get; set; }
        public int CLAVE_PERSO { get; set; }
        public int CLA_MOTI { get; set; }
        public System.DateTime FEC_SASEP { get; set; }
        public string HORA_SASEP { get; set; }
        public int CLA_DISPO { get; set; }
        public int CLA_AUTO { get; set; }
        public string CLA_EDO { get; set; }
        public int NUM_PERSO { get; set; }
        public string SAL_LIBRE { get; set; }
        public int SalCeldas { get; set; }
        public int Id { get; set; }
        public string Perso_Encontraba { get; set; }
        public System.DateTime Fec_Captu { get; set; }
        public int AutorIntelectual { get; set; }
        public System.Guid rowguid { get; set; }
        public string Cla_Edo_Anterior { get; set; }
        public string Cla_Edo_Nuevo { get; set; }
        public string CoordX { get; set; }
        public string CoordY { get; set; }
        public string MapaLogin { get; set; }
        public int MapaCve_Usuario { get; set; }
        public System.DateTime MapaFechaAct { get; set; }
        public string MapaHoraAct { get; set; }
        public string MapaLogin_Red { get; set; }
    }
}
