//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Mandamientos_JudicialesEntities : DbContext
    {
        public Mandamientos_JudicialesEntities()
            : base("name=Mandamientos_JudicialesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_ObjPri_getObjetivoInfo_Result> sp_ObjPri_getObjetivoInfo(Nullable<int> movimiento, string nombre, string paterno, string materno, string numavp, Nullable<int> id_mandamiento)
        {
            var movimientoParameter = movimiento.HasValue ?
                new ObjectParameter("movimiento", movimiento) :
                new ObjectParameter("movimiento", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            var numavpParameter = numavp != null ?
                new ObjectParameter("numavp", numavp) :
                new ObjectParameter("numavp", typeof(string));
    
            var id_mandamientoParameter = id_mandamiento.HasValue ?
                new ObjectParameter("id_mandamiento", id_mandamiento) :
                new ObjectParameter("id_mandamiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ObjPri_getObjetivoInfo_Result>("sp_ObjPri_getObjetivoInfo", movimientoParameter, nombreParameter, paternoParameter, maternoParameter, numavpParameter, id_mandamientoParameter);
        }
    
        public virtual ObjectResult<SP_ObjPri_getListinfogeneral_Result> SP_ObjPri_getListinfogeneral(string nombre, string paterno, string materno)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ObjPri_getListinfogeneral_Result>("SP_ObjPri_getListinfogeneral", nombreParameter, paternoParameter, maternoParameter);
        }
    }
}
