//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mandamiento_judicial
    {
        public int id { get; set; }
        public string numero_control { get; set; }
        public string numero_expediente_juzgado { get; set; }
        public string numero_expediente { get; set; }
        public int id_tipo_mandato { get; set; }
        public int id_juzgado { get; set; }
        public int id_sexo { get; set; }
        public string numero_oficio_juzgado { get; set; }
        public string requerido_por { get; set; }
        public System.DateTime fecha_expedicion { get; set; }
        public System.DateTime fecha_recepcion { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public Nullable<int> id_estado_proceso { get; set; }
        public Nullable<int> domicilio { get; set; }
        public int id_estado_origen_mandamiento { get; set; }
        public Nullable<int> id_grupo_cumple_orden { get; set; }
        public Nullable<int> id_grupo_cumplio_turno { get; set; }
        public int clave_usuario { get; set; }
    }
}
