//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ministerios
    {
        public int Cve_Usuario { get; set; }
        public short Cve_Age { get; set; }
        public Nullable<short> Cve_Titulo { get; set; }
        public bool Secretario { get; set; }
        public string Usuario { get; set; }
        public string Equipo { get; set; }
        public string Aplicacion { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
