//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipio
    {
        public int Cve_mun { get; set; }
        public string Municipio1 { get; set; }
        public string Cve_edo { get; set; }
        public int SNSP_Cla_Mpio { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> FK_Estado { get; set; }
    }
}
