//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Objetivos_PrioritariosEntities : DbContext
    {
        public Objetivos_PrioritariosEntities()
            : base("name=Objetivos_PrioritariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_EstatusAsunto> cat_EstatusAsunto { get; set; }
        public virtual DbSet<cat_EstatusProceso> cat_EstatusProceso { get; set; }
        public virtual DbSet<cat_TipoActividadDelictiva> cat_TipoActividadDelictiva { get; set; }
        public virtual DbSet<cat_TipoAgrupacion> cat_TipoAgrupacion { get; set; }
        public virtual DbSet<tb_AlbumFichaObjetivo> tb_AlbumFichaObjetivo { get; set; }
        public virtual DbSet<tb_AlbumFichaObjetivoDetalle> tb_AlbumFichaObjetivoDetalle { get; set; }
        public virtual DbSet<tb_AliasObjetivo> tb_AliasObjetivo { get; set; }
        public virtual DbSet<tb_AsuntoRelacionado> tb_AsuntoRelacionado { get; set; }
        public virtual DbSet<tb_AsuntoVictimas> tb_AsuntoVictimas { get; set; }
        public virtual DbSet<tb_CarpetasObjetivo> tb_CarpetasObjetivo { get; set; }
        public virtual DbSet<tb_Detenido> tb_Detenido { get; set; }
        public virtual DbSet<tb_Detenidos_DelitoIngreso> tb_Detenidos_DelitoIngreso { get; set; }
        public virtual DbSet<tb_FichaAsunto> tb_FichaAsunto { get; set; }
        public virtual DbSet<tb_FichaObjetivo> tb_FichaObjetivo { get; set; }
        public virtual DbSet<tb_Grupo_Delictivo> tb_Grupo_Delictivo { get; set; }
        public virtual DbSet<tb_GrupoTipoActividadDelictiva> tb_GrupoTipoActividadDelictiva { get; set; }
        public virtual DbSet<tb_InformacionObjetivo> tb_InformacionObjetivo { get; set; }
        public virtual DbSet<tb_NombreObjetivo> tb_NombreObjetivo { get; set; }
        public virtual DbSet<tb_Objetivo> tb_Objetivo { get; set; }
        public virtual DbSet<tb_ObjetivoGrupo> tb_ObjetivoGrupo { get; set; }
        public virtual DbSet<tb_OrdenAprehension> tb_OrdenAprehension { get; set; }
        public virtual DbSet<tb_Usuarios> tb_Usuarios { get; set; }
        public virtual DbSet<tb_Victimas> tb_Victimas { get; set; }
    
        public virtual ObjectResult<getInfoObjetivoList_Result> getInfoObjetivoList(Nullable<int> int_id_objetivo, Nullable<bool> bit_estatus)
        {
            var int_id_objetivoParameter = int_id_objetivo.HasValue ?
                new ObjectParameter("int_id_objetivo", int_id_objetivo) :
                new ObjectParameter("int_id_objetivo", typeof(int));
    
            var bit_estatusParameter = bit_estatus.HasValue ?
                new ObjectParameter("bit_estatus", bit_estatus) :
                new ObjectParameter("bit_estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInfoObjetivoList_Result>("getInfoObjetivoList", int_id_objetivoParameter, bit_estatusParameter);
        }
    
        public virtual ObjectResult<getInfoObjetivoListById_Result> getInfoObjetivoListById(Nullable<int> int_id_informacion)
        {
            var int_id_informacionParameter = int_id_informacion.HasValue ?
                new ObjectParameter("int_id_informacion", int_id_informacion) :
                new ObjectParameter("int_id_informacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInfoObjetivoListById_Result>("getInfoObjetivoListById", int_id_informacionParameter);
        }
    
        public virtual ObjectResult<getListFiliacionRelacionada_Result> getListFiliacionRelacionada(Nullable<int> int_id_ficha_objetivo, Nullable<bool> active)
        {
            var int_id_ficha_objetivoParameter = int_id_ficha_objetivo.HasValue ?
                new ObjectParameter("int_id_ficha_objetivo", int_id_ficha_objetivo) :
                new ObjectParameter("int_id_ficha_objetivo", typeof(int));
    
            var activeParameter = active.HasValue ?
                new ObjectParameter("active", active) :
                new ObjectParameter("active", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListFiliacionRelacionada_Result>("getListFiliacionRelacionada", int_id_ficha_objetivoParameter, activeParameter);
        }
    
        public virtual ObjectResult<getNamePhotoList_Result> getNamePhotoList(string nombre, string paterno, string materno)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getNamePhotoList_Result>("getNamePhotoList", nombreParameter, paternoParameter, maternoParameter);
        }
    
        public virtual ObjectResult<getListVictimasByNombre_Result> getListVictimasByNombre(string nombre, string paterno, string materno, Nullable<int> opcion, Nullable<bool> bit_status)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(int));
    
            var bit_statusParameter = bit_status.HasValue ?
                new ObjectParameter("bit_status", bit_status) :
                new ObjectParameter("bit_status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListVictimasByNombre_Result>("getListVictimasByNombre", nombreParameter, paternoParameter, maternoParameter, opcionParameter, bit_statusParameter);
        }
    
        public virtual ObjectResult<getListObjetivosPrioritarios_Result> getListObjetivosPrioritarios(Nullable<bool> bit_estatus)
        {
            var bit_estatusParameter = bit_estatus.HasValue ?
                new ObjectParameter("bit_estatus", bit_estatus) :
                new ObjectParameter("bit_estatus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListObjetivosPrioritarios_Result>("getListObjetivosPrioritarios", bit_estatusParameter);
        }
    
        public virtual ObjectResult<getListObjetivosRelacionadoAsunto_Result> getListObjetivosRelacionadoAsunto(Nullable<bool> bit_estatus, Nullable<int> int_id_asunto_relacionado)
        {
            var bit_estatusParameter = bit_estatus.HasValue ?
                new ObjectParameter("bit_estatus", bit_estatus) :
                new ObjectParameter("bit_estatus", typeof(bool));
    
            var int_id_asunto_relacionadoParameter = int_id_asunto_relacionado.HasValue ?
                new ObjectParameter("int_id_asunto_relacionado", int_id_asunto_relacionado) :
                new ObjectParameter("int_id_asunto_relacionado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListObjetivosRelacionadoAsunto_Result>("getListObjetivosRelacionadoAsunto", bit_estatusParameter, int_id_asunto_relacionadoParameter);
        }
    
        public virtual ObjectResult<getListObjetivosRelacionadoGrupo_Result> getListObjetivosRelacionadoGrupo(Nullable<bool> bit_estatus, Nullable<int> int_id_album_ficha_objetivo)
        {
            var bit_estatusParameter = bit_estatus.HasValue ?
                new ObjectParameter("bit_estatus", bit_estatus) :
                new ObjectParameter("bit_estatus", typeof(bool));
    
            var int_id_album_ficha_objetivoParameter = int_id_album_ficha_objetivo.HasValue ?
                new ObjectParameter("int_id_album_ficha_objetivo", int_id_album_ficha_objetivo) :
                new ObjectParameter("int_id_album_ficha_objetivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getListObjetivosRelacionadoGrupo_Result>("getListObjetivosRelacionadoGrupo", bit_estatusParameter, int_id_album_ficha_objetivoParameter);
        }
    }
}
