//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Objetivos_Prioritarios_Perfiles_Entities : DbContext
    {
        public Objetivos_Prioritarios_Perfiles_Entities()
            : base("name=Objetivos_Prioritarios_Perfiles_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_FuenteBusqueda> cat_FuenteBusqueda { get; set; }
        public virtual DbSet<cat_ModuloSistema> cat_ModuloSistema { get; set; }
        public virtual DbSet<cat_Perfil> cat_Perfil { get; set; }
        public virtual DbSet<cat_PermisoSistema> cat_PermisoSistema { get; set; }
        public virtual DbSet<tb_PerfilFuenteBusqueda> tb_PerfilFuenteBusqueda { get; set; }
        public virtual DbSet<tb_PerfilModulo> tb_PerfilModulo { get; set; }
        public virtual DbSet<tb_PerfilPermiso> tb_PerfilPermiso { get; set; }
        public virtual DbSet<tb_UsuarioPerfil> tb_UsuarioPerfil { get; set; }
        public virtual DbSet<tb_Usuarios> tb_Usuarios { get; set; }
    }
}
