//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int CLAVE_PERSO { get; set; }
        public string NUM_FICH { get; set; }
        public string NUM_FILIA { get; set; }
        public int CLA_CALLE { get; set; }
        public string NUM_CASA { get; set; }
        public string ESTATURA { get; set; }
        public string DIES_SINIES { get; set; }
        public int CLA_OCUPA { get; set; }
        public string LTRABAJO { get; set; }
        public System.DateTime FEC_NAC { get; set; }
        public string OBSERVA { get; set; }
        public string PESO { get; set; }
        public string EDAD { get; set; }
        public string CLA_EDO { get; set; }
        public string SEXO { get; set; }
        public string FORMULA { get; set; }
        public System.DateTime FEC_FILI { get; set; }
        public int C_PIEL { get; set; }
        public int C_PELO { get; set; }
        public int CARAC_PEL { get; set; }
        public int C_OJOS { get; set; }
        public int COMPLEXI { get; set; }
        public int CEJAS { get; set; }
        public int LABIOS { get; set; }
        public int BOCA { get; set; }
        public int NARIZ1 { get; set; }
        public int NARIZ2 { get; set; }
        public int NARIZ3 { get; set; }
        public int FRENTE { get; set; }
        public int MENTON1 { get; set; }
        public int MENTON2 { get; set; }
        public int TIPCARA { get; set; }
        public int ESPANAZO { get; set; }
        public int INSEPEL { get; set; }
        public int CALVICIE { get; set; }
        public string NCP { get; set; }
        public string IDECRIM { get; set; }
        public int PAISNAC { get; set; }
        public int MUNINAC { get; set; }
        public int NACIONALIDAD { get; set; }
        public string CIVIL { get; set; }
        public string TELEFONO { get; set; }
        public int LENTES { get; set; }
        public Nullable<System.DateTime> FECHANCP { get; set; }
        public int Verificador { get; set; }
        public string Ubi_Lu_Trabajo { get; set; }
        public string Telefono_Trabajo { get; set; }
        public int Tipo_Casa { get; set; }
        public string Nombre_Esposa { get; set; }
        public string Paterno_Esposa { get; set; }
        public string Materno_Esposa { get; set; }
        public string Nombre_Padre { get; set; }
        public string Paterno_Padre { get; set; }
        public string Materno_Padre { get; set; }
        public int Vivo_Padre { get; set; }
        public string Domicilio_Padre { get; set; }
        public string Nombre_Madre { get; set; }
        public string Paterno_Madre { get; set; }
        public string Materno_Madre { get; set; }
        public int Vivo_Madre { get; set; }
        public string Domicilio_Madre { get; set; }
        public string Avisar_Telefono { get; set; }
        public string Avisar_Nombre_Persona { get; set; }
        public string Avisar_Paterno_Persona { get; set; }
        public string Avisar_Materno_Persona { get; set; }
        public string Avisar_Domicilio { get; set; }
        public System.DateTime Fec_Captu { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<int> Cla_Calle_Anterior { get; set; }
        public Nullable<int> Cla_Calle_Nuevo { get; set; }
        public Nullable<int> Cla_Ocupa_Anterior { get; set; }
        public Nullable<int> Cla_Ocupa_Nuevo { get; set; }
        public string Cla_Edo_Anterior { get; set; }
        public string Cla_Edo_Nuevo { get; set; }
        public Nullable<int> MuniNac_Anterior { get; set; }
        public Nullable<int> MuniNac_Nuevo { get; set; }
        public Nullable<int> Nacionalidad_Anterior { get; set; }
        public Nullable<int> Nacionalidad_Nuevo { get; set; }
        public Nullable<int> PaisNac_Anterior { get; set; }
        public Nullable<int> PaisNac_Nuevo { get; set; }
        public int Vivo_Det { get; set; }
        public string CoordX { get; set; }
        public string CoordY { get; set; }
        public string MapaLogin { get; set; }
        public int MapaCve_Usuario { get; set; }
        public System.DateTime MapaFechaAct { get; set; }
        public string MapaHoraAct { get; set; }
        public string MapaLogin_Red { get; set; }
    }
}
