//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SICEntities : DbContext
    {
        public SICEntities()
            : base("name=SICEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COINCIDENCIA> COINCIDENCIA { get; set; }
        public virtual DbSet<DETENCION> DETENCION { get; set; }
        public virtual DbSet<DETENIDO> DETENIDO { get; set; }
        public virtual DbSet<FOTO> FOTO { get; set; }
        public virtual DbSet<Modulos> Modulos { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Usuario_Modulos> Usuario_Modulos { get; set; }
    }
}
