//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalDetenidosEntities : DbContext
    {
        public PortalDetenidosEntities()
            : base("name=PortalDetenidosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cat_Faltas> Cat_Faltas { get; set; }
        public virtual DbSet<DETENCION> DETENCION { get; set; }
        public virtual DbSet<DETENIDO> DETENIDO { get; set; }
        public virtual DbSet<FOTO> FOTO { get; set; }
        public virtual DbSet<Huella> Huella { get; set; }
        public virtual DbSet<CAT_Municipio> CAT_Municipio { get; set; }
    }
}
