//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIPJEntities : DbContext
    {
        public SIPJEntities()
            : base("name=SIPJEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Sp_ObjPri_getCarpetasList_Result> Sp_ObjPri_getCarpetasList(Nullable<int> movimiento, string nombre, string paterno, string materno, string numavp)
        {
            var movimientoParameter = movimiento.HasValue ?
                new ObjectParameter("movimiento", movimiento) :
                new ObjectParameter("movimiento", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var paternoParameter = paterno != null ?
                new ObjectParameter("paterno", paterno) :
                new ObjectParameter("paterno", typeof(string));
    
            var maternoParameter = materno != null ?
                new ObjectParameter("materno", materno) :
                new ObjectParameter("materno", typeof(string));
    
            var numavpParameter = numavp != null ?
                new ObjectParameter("numavp", numavp) :
                new ObjectParameter("numavp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_ObjPri_getCarpetasList_Result>("Sp_ObjPri_getCarpetasList", movimientoParameter, nombreParameter, paternoParameter, maternoParameter, numavpParameter);
        }
    }
}
