//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_AsuntoRelacionado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_AsuntoRelacionado()
        {
            this.tb_AsuntoVictimas = new HashSet<tb_AsuntoVictimas>();
            this.tb_FichaAsunto = new HashSet<tb_FichaAsunto>();
        }
    
        public int int_id_asunto_relacionado { get; set; }
        public string nvarchar_alias { get; set; }
        public string nvarchar_descripcion { get; set; }
        public Nullable<System.DateTime> date_fecha_asunto { get; set; }
        public string numavp { get; set; }
        public Nullable<int> int_id_estatus_asunto { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        public virtual cat_EstatusAsunto cat_EstatusAsunto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AsuntoVictimas> tb_AsuntoVictimas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FichaAsunto> tb_FichaAsunto { get; set; }
    }
}
