//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Alerta
    {
        public int idAlerta { get; set; }
        public Nullable<int> idPersonaFGEA { get; set; }
        public Nullable<int> idTipoAlerta { get; set; }
        public int IdTbFuente { get; set; }
        public Nullable<System.DateTime> FechaAlerta { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> idDetenidoC5 { get; set; }
        public Nullable<int> Porcentaje { get; set; }
    
        public virtual cat_EstatusAlerta cat_EstatusAlerta { get; set; }
        public virtual cat_TbFuente cat_TbFuente { get; set; }
        public virtual cat_TipoAlerta cat_TipoAlerta { get; set; }
    }
}
