//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Detencion_C5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Detencion_C5()
        {
            this.tb_Detenido_C5 = new HashSet<tb_Detenido_C5>();
        }
    
        public int IDDETENCION { get; set; }
        public string SERIE_MUNICIPIO { get; set; }
        public string CONSECUTIVO { get; set; }
        public string ANO { get; set; }
        public Nullable<System.DateTime> FECHA_DETENCION { get; set; }
        public string HORA_DETENCION { get; set; }
        public string FUERO { get; set; }
        public Nullable<int> NoDETENIDOS { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string CP { get; set; }
        public string MUNICIPIO { get; set; }
        public string HECHO { get; set; }
        public string CAUSA { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<bool> VECHICULO { get; set; }
        public Nullable<int> NUMEXT { get; set; }
        public string NUMINT { get; set; }
        public string Mes { get; set; }
        public string Dia { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public string FueroDescripcion { get; set; }
        public Nullable<int> idUsuarioCrea { get; set; }
        public Nullable<int> idUsuarioTraslada { get; set; }
    
        public virtual tb_Usuario_C5 tb_Usuario_C5 { get; set; }
        public virtual tb_Usuario_C5 tb_Usuario_C51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detenido_C5> tb_Detenido_C5 { get; set; }
    }
}
