//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Domicilio
    {
        public int idDomicilio { get; set; }
        public int idPersona { get; set; }
        public Nullable<int> Cve_Calle { get; set; }
        public Nullable<int> NumInt { get; set; }
        public Nullable<int> NumExt { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int UsuarioRegistro { get; set; }
        public Nullable<int> Tipo { get; set; }
    
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
