//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Detenido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Detenido()
        {
            this.tb_Detenidos_DelitoIngreso = new HashSet<tb_Detenidos_DelitoIngreso>();
        }
    
        public int int_id_detenido { get; set; }
        public int int_id_ficha_objetivo { get; set; }
        public string numavp { get; set; }
        public Nullable<System.DateTime> date_fecha_detencion { get; set; }
        public Nullable<System.TimeSpan> time_hora_detencion { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
        public Nullable<int> clave_persona { get; set; }
        public Nullable<System.DateTime> date_fecha_ingreso { get; set; }
        public Nullable<System.DateTime> date_fecha_captura_filiacion { get; set; }
    
        public virtual tb_FichaObjetivo tb_FichaObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detenidos_DelitoIngreso> tb_Detenidos_DelitoIngreso { get; set; }
    }
}
