//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Detenidos_DelitoIngreso
    {
        public int int_id_delito_ingreso { get; set; }
        public int int_id_detenido { get; set; }
        public int Cve_Delito { get; set; }
        public string Delito { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        public virtual tb_Detenido tb_Detenido { get; set; }
    }
}
