//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_FichaObjetivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_FichaObjetivo()
        {
            this.tb_AlbumFichaObjetivoDetalle = new HashSet<tb_AlbumFichaObjetivoDetalle>();
            this.tb_CarpetasObjetivo = new HashSet<tb_CarpetasObjetivo>();
            this.tb_Detenido = new HashSet<tb_Detenido>();
            this.tb_FichaAsunto = new HashSet<tb_FichaAsunto>();
            this.tb_OrdenAprehension = new HashSet<tb_OrdenAprehension>();
        }
    
        public int int_id_ficha_objetivo { get; set; }
        public int int_id_objetivo { get; set; }
        public Nullable<int> int_id_estatus_proceso { get; set; }
        public string nvarchar_descripcion_estatus { get; set; }
        public string nvarchar_observaciones { get; set; }
        public Nullable<bool> bit_estatus { get; set; }
    
        public virtual cat_EstatusProceso cat_EstatusProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AlbumFichaObjetivoDetalle> tb_AlbumFichaObjetivoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CarpetasObjetivo> tb_CarpetasObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detenido> tb_Detenido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FichaAsunto> tb_FichaAsunto { get; set; }
        public virtual tb_Objetivo tb_Objetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrdenAprehension> tb_OrdenAprehension { get; set; }
    }
}
