//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Grupo_Delictivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Grupo_Delictivo()
        {
            this.tb_GrupoTipoActividadDelictiva = new HashSet<tb_GrupoTipoActividadDelictiva>();
            this.tb_ObjetivoGrupo = new HashSet<tb_ObjetivoGrupo>();
        }
    
        public int int_id_grupo { get; set; }
        public string nvarchar_alias { get; set; }
        public string nvarchar_grupo { get; set; }
        public int int_id_tipo_agrupacion { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        public virtual cat_TipoAgrupacion cat_TipoAgrupacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_GrupoTipoActividadDelictiva> tb_GrupoTipoActividadDelictiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ObjetivoGrupo> tb_ObjetivoGrupo { get; set; }
    }
}
