//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_InformacionObjetivo
    {
        public int int_id_informacion { get; set; }
        public Nullable<int> Cve_Calle { get; set; }
        public string nvarchar_no_casa { get; set; }
        public string nvarchar_observaciones { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public string nvarchar_usuario_creacion { get; set; }
        public bool bit_estatus { get; set; }
        public int int_id_objetivo { get; set; }
        public string nvarchar_cp { get; set; }
        public int int_clave_perso { get; set; }
    
        public virtual tb_Objetivo tb_Objetivo { get; set; }
    }
}
