//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NombreObjetivo
    {
        public int int_id_nombre { get; set; }
        public string nvarchar_nombre { get; set; }
        public string nvarchar_paterno { get; set; }
        public string nvarchar_materno { get; set; }
        public int int_id_objetivo { get; set; }
        public Nullable<System.DateTime> date_fecha_creacion { get; set; }
        public string nvarchar_usuario_creacion { get; set; }
        public Nullable<bool> bit_estatus { get; set; }
        public int int_clave_perso { get; set; }
        public int int_id_nombre_filiacion { get; set; }
        public Nullable<bool> bit_principal { get; set; }
    
        public virtual tb_Objetivo tb_Objetivo { get; set; }
    }
}
