//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Objetivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Objetivo()
        {
            this.tb_AliasObjetivo = new HashSet<tb_AliasObjetivo>();
            this.tb_FichaObjetivo = new HashSet<tb_FichaObjetivo>();
            this.tb_InformacionObjetivo = new HashSet<tb_InformacionObjetivo>();
            this.tb_NombreObjetivo = new HashSet<tb_NombreObjetivo>();
            this.tb_ObjetivoGrupo = new HashSet<tb_ObjetivoGrupo>();
        }
    
        public int int_id_objetivo { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public string nvarchar_usuario_creacion { get; set; }
        public bool bit_estatus { get; set; }
        public string nvarchar_foto { get; set; }
        public Nullable<System.DateTime> date_fecha_nacimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AliasObjetivo> tb_AliasObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FichaObjetivo> tb_FichaObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_InformacionObjetivo> tb_InformacionObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_NombreObjetivo> tb_NombreObjetivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ObjetivoGrupo> tb_ObjetivoGrupo { get; set; }
    }
}
