//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OrdenAprehension
    {
        public int int_id_orden_aprehension { get; set; }
        public int int_id_ficha_objetivo { get; set; }
        public int id_mandamiento_judicial { get; set; }
        public int id_delito { get; set; }
        public string delito { get; set; }
        public Nullable<int> id_estado_proceso { get; set; }
        public string tipo { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
        public Nullable<System.DateTime> date_fecha_estatus { get; set; }
    
        public virtual tb_FichaObjetivo tb_FichaObjetivo { get; set; }
    }
}
