//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ObjetivoGrupo
    {
        public int int_id_objetivo_grupo { get; set; }
        public int int_id_objetivo { get; set; }
        public int int_id_grupo { get; set; }
        public Nullable<System.DateTime> date_fecha_ingreso { get; set; }
        public Nullable<System.DateTime> date_fecha_salida { get; set; }
        public string nvarchar_observaciones { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        public virtual tb_Grupo_Delictivo tb_Grupo_Delictivo { get; set; }
        public virtual tb_Objetivo tb_Objetivo { get; set; }
    }
}
