//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Persona()
        {
            this.tb_Detencion = new HashSet<tb_Detencion>();
            this.tb_Domicilio = new HashSet<tb_Domicilio>();
            this.tb_Fotografia = new HashSet<tb_Fotografia>();
            this.tb_SenasParticulares = new HashSet<tb_SenasParticulares>();
            this.tb_PersonaAlias = new HashSet<tb_PersonaAlias>();
            this.tb_PersonaPeriodoBusqueda = new HashSet<tb_PersonaPeriodoBusqueda>();
        }
    
        public int idPersona { get; set; }
        public string Nombre { get; set; }
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string Estatura { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int UsuarioRegistro { get; set; }
        public string Observaciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detencion> tb_Detencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Domicilio> tb_Domicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Fotografia> tb_Fotografia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SenasParticulares> tb_SenasParticulares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PersonaAlias> tb_PersonaAlias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PersonaPeriodoBusqueda> tb_PersonaPeriodoBusqueda { get; set; }
    }
}
