//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PerfilFuenteBusqueda
    {
        public int int_id_perfil_fuente { get; set; }
        public int int_id_perfil { get; set; }
        public int int_id_fuente { get; set; }
        public bool bit_status { get; set; }
        public System.DateTime date_fecha_alta { get; set; }
        public Nullable<System.DateTime> date_fecha_modificacion { get; set; }
        public string nvarchar_usuario_modificacion { get; set; }
    
        public virtual cat_FuenteBusqueda cat_FuenteBusqueda { get; set; }
        public virtual cat_Perfil cat_Perfil { get; set; }
    }
}
