//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PersonaSourceAFIS
    {
        public int IdPersona { get; set; }
        public byte[] SourceAFIS { get; set; }
        public int IdTbFuente { get; set; }
        public Nullable<bool> Activo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual cat_TbFuente cat_TbFuente { get; set; }
    }
}
