//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PersonaPeriodoBusqueda
    {
        public int idPeriodoBusqueda { get; set; }
        public int idPersona { get; set; }
        public System.DateTime FechaInicioBusqueda { get; set; }
        public Nullable<System.DateTime> FechaFinBusqueda { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioRegistro { get; set; }
        public bool Activo { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> UsuarioCancelacion { get; set; }
        public string MotivoCancelacion { get; set; }
        public int idEstatusPeriodoBusqueda { get; set; }
    
        public virtual cat_EstatusPeriodoBusqueda cat_EstatusPeriodoBusqueda { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
