//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PagoMulta_C5
    {
        public int IdPagoMulta { get; set; }
        public int IdResolucionJuez { get; set; }
        public int IdDetenido { get; set; }
        public string FolioRecibo { get; set; }
        public decimal MontoTotalMulta { get; set; }
        public decimal MontoPagado { get; set; }
        public decimal MontoPendiente { get; set; }
        public string FormaPago { get; set; }
        public string EstatusPago { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public int idUsuarioRecibe { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
