//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SenasParticulares
    {
        public int idSena { get; set; }
        public int idPersona { get; set; }
        public int IdTipoSena { get; set; }
        public int IdZona { get; set; }
        public string Descripcion { get; set; }
        public string RutaArchivo { get; set; }
        public string ArchivoB64 { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public int UsuarioRegistro { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
