//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TrabajoSocial_C5
    {
        public int ID_SERVICIO_SOCIAL { get; set; }
        public Nullable<int> IDDETENIDO { get; set; }
        public string ExpedienteNo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string EstructuraFamiliarJson { get; set; }
        public Nullable<decimal> IngresoMensual { get; set; }
        public Nullable<int> DependientesEconomicos { get; set; }
        public Nullable<decimal> GastoAlimentacion { get; set; }
        public Nullable<decimal> GastoEducacion { get; set; }
        public Nullable<decimal> GastoTransporte { get; set; }
        public Nullable<decimal> GastoAgua { get; set; }
        public Nullable<decimal> GastoLuz { get; set; }
        public Nullable<decimal> GastoGas { get; set; }
        public Nullable<decimal> GastoSalud { get; set; }
        public Nullable<decimal> GastoOtro { get; set; }
        public Nullable<decimal> EgresoMensual { get; set; }
        public string TenenciaVivienda { get; set; }
        public string ServicioSalud { get; set; }
        public string NivelSocioeconomico { get; set; }
        public string DiagnosticoSocialTexto { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string ColoniaFracc { get; set; }
        public string Domicilio { get; set; }
        public string Edad { get; set; }
        public string Escolaridad { get; set; }
        public string EstadoCivil { get; set; }
        public string FechaNacimiento { get; set; }
        public string LugarNacimiento { get; set; }
        public string Municipio { get; set; }
        public string Nacionalidad { get; set; }
        public string Nombre { get; set; }
        public string Ocupacion { get; set; }
        public string Telefono { get; set; }
        public string UsuarioRegistro { get; set; }
    
        public virtual tb_Detenido_C5 tb_Detenido_C5 { get; set; }
        public virtual tb_Usuario_C5 tb_Usuario_C5 { get; set; }
    }
}
