//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuario_C5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Usuario_C5()
        {
            this.tb_Detencion_C5 = new HashSet<tb_Detencion_C5>();
            this.tb_Detencion_C51 = new HashSet<tb_Detencion_C5>();
            this.tb_Detenido_C5 = new HashSet<tb_Detenido_C5>();
            this.tb_FotoRasgos_C5 = new HashSet<tb_FotoRasgos_C5>();
            this.tb_TrabajoSocial_C5 = new HashSet<tb_TrabajoSocial_C5>();
        }
    
        public int idUsuario { get; set; }
        public string Usuario { get; set; }
        public string App { get; set; }
        public string Apm { get; set; }
        public string Nombre { get; set; }
        public string Grupo { get; set; }
        public string Unidad { get; set; }
        public string Corporacion { get; set; }
        public string Municipio { get; set; }
        public string Turno { get; set; }
        public string Grado { get; set; }
        public string Rol { get; set; }
        public bool Estatus { get; set; }
        public string Cedula { get; set; }
        public string SSA { get; set; }
        public Nullable<int> NoEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detencion_C5> tb_Detencion_C5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detencion_C5> tb_Detencion_C51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Detenido_C5> tb_Detenido_C5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_FotoRasgos_C5> tb_FotoRasgos_C5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_TrabajoSocial_C5> tb_TrabajoSocial_C5 { get; set; }
    }
}
