//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Usuarios()
        {
            this.tb_UsuarioPerfil = new HashSet<tb_UsuarioPerfil>();
        }
    
        public int int_id_usuario { get; set; }
        public string nvarchar_nombre_usuario { get; set; }
        public string nvarchar_no_interno { get; set; }
        public string nvarchar_puesto { get; set; }
        public System.DateTime date_fecha_alta { get; set; }
        public Nullable<bool> bit_status { get; set; }
        public Nullable<System.DateTime> date_fecha_modificacion { get; set; }
        public string nvarchar_usuario_modificacion { get; set; }
        public Nullable<int> Valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_UsuarioPerfil> tb_UsuarioPerfil { get; set; }
    }
}
