//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Victimas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Victimas()
        {
            this.tb_AsuntoVictimas = new HashSet<tb_AsuntoVictimas>();
        }
    
        public int int_id_victima { get; set; }
        public string nvarchar_nombre { get; set; }
        public string nvarchar_paterno { get; set; }
        public string nvarchar_materno { get; set; }
        public string nvarchar_foto { get; set; }
        public System.DateTime date_fecha_creacion { get; set; }
        public bool bit_estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_AsuntoVictimas> tb_AsuntoVictimas { get; set; }
    }
}
