//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string Paterno { get; set; }
        public string Materno { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public Nullable<int> Cve_DirFGE { get; set; }
        public Nullable<decimal> Area { get; set; }
        public string Password { get; set; }
        public string Login { get; set; }
        public string Usu_DoctosSEGI { get; set; }
        public string Pas_DoctosSEGI { get; set; }
        public string Calle { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public decimal Cve_Usuario { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Baja { get; set; }
        public string Cve_Presupuestal { get; set; }
        public string RFC { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public string Tipo_Sangre { get; set; }
        public string Horario { get; set; }
        public string NoPgr { get; set; }
        public string NoImss { get; set; }
        public string Curp { get; set; }
        public string Cuip { get; set; }
        public Nullable<decimal> Cve_Baja { get; set; }
        public string Baja { get; set; }
        public string DondeVer { get; set; }
        public string No_Casa { get; set; }
        public string CP { get; set; }
        public string Cve_Civil { get; set; }
        public Nullable<decimal> Gafete { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> Cve_Puesto { get; set; }
        public string Comentario { get; set; }
        public string Direccion { get; set; }
        public string Sexo { get; set; }
        public string Lugar_Nac { get; set; }
        public string E_mail { get; set; }
        public string C_Barra { get; set; }
        public Nullable<int> Cve_categoria { get; set; }
        public Nullable<System.DateTime> fecha_password { get; set; }
        public int Cve_Horario { get; set; }
        public System.Guid rowguid { get; set; }
        public string Numero_Empleado { get; set; }
        public string Partida_Presupuestal { get; set; }
        public int Cve_Categoria_Puesto { get; set; }
        public byte[] Huella_IB { get; set; }
        public int Cve_Clinica { get; set; }
        public Nullable<bool> Donador_Organos { get; set; }
        public string Password_SIANET { get; set; }
        public int id_area_real { get; set; }
    }
}
