//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Objetivos_Prioritarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasena { get; set; }
        public string App { get; set; }
        public string Apm { get; set; }
        public string Nombre { get; set; }
        public string Grupo { get; set; }
        public string Unidad { get; set; }
        public string Corporacion { get; set; }
        public string Municipio { get; set; }
        public string Turno { get; set; }
        public string Grado { get; set; }
        public string Rol { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Cedula { get; set; }
        public string SSA { get; set; }
    }
}
